spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: auth
    password: auth
  jpa:
    # Flyway controla o schema; aqui apenas validamos
    hibernate.ddl-auto: validate
    properties.hibernate.format_sql: true
  thymeleaf:
    cache: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  jwt:
    issuer: example-auth            # claim "iss" do token
    access-ttl-min: 15              # tempo do access (min)
    refresh-ttl-days: 7             # tempo do refresh (dias)
    # Secret em Base64 (≥256 bits). Produção: usar env JWT_SECRET
    secret: ${JWT_SECRET:VGhpcy1pcy1qd3Qtc2VjcmV0LWJhc2U2NC1wbGFjZWhvbGRlci0xMjM0NTY3ODkwMTIzNDU2}
  cookies:
    domain: localhost               # ajuste no deploy (ex.: .minhaapp.com)
    secure: false                   # true em produção (HTTPS)
    same-site: Lax                  # Lax para formulários; cross-site real: None+Secure
  security:
    reset-token-expiration-minutes: 30
    base-url: http://localhost:8080
